Models/Cinephile.cs
using Microsoft.AspNetCore.Identity;

namespace Proyect_Rotten_Tomatoes.Models
{
    public class Cinephile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public List<FavouriteMovies> FavouriteMovies { get; set; }
        public List<FavouriteSeries> FavouriteSeries { get; set; }
    }
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proyect_Rotten_Tomatoes.Data;
using Proyect_Rotten_Tomatoes.Models;

namespace Proyect_Rotten_Tomatoes.Controllers
{
    public class MoviesController : Controller
    {
        private readonly Proyect_Rotten_TomatoesContext _context;

        public MoviesController(Proyect_Rotten_TomatoesContext context)
        {
            _context = context;
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Movie == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string url)
        {
            if (string.IsNullOrEmpty(url))
            {
                ModelState.AddModelError("url", "Link is required."); // Add validation error to ModelState
                return View();
            }
            try
            {
                Movie movie = WebScraper.Get_Movie_data(url);
                if (await _context.Movie.SingleOrDefaultAsync(m => m.Title == movie.Title) != null)
                {
                    throw new Exception("Movie already exists");
                }
                _context.Add(movie);
        }
            catch (Exception)
            {
                ModelState.AddModelError("url", "Try another link.");
                return View();
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Film_ExpertMovies", "Film_Expert");
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Movie == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,url,Title,Image,Critic_Rating,Audience_Rating,Critic_Comments,Audience_Comments,Available_Platforms,Synopsis,Rating,Genre,Film_Team,Duration,Principal_Actors,Release_Date,Top")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Film_ExpertMovies", "Film_Expert");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Movie == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Movie == null)
            {
                return Problem("Entity set 'Proyect_Rotten_TomatoesContext.Movie'  is null.");
            }
            var movie = await _context.Movie.FindAsync(id);
            if (movie != null)
            {
                _context.Movie.Remove(movie);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Film_ExpertMovies", "Film_Expert");
        }

        private bool MovieExists(int id)
        {
            return (_context.Movie?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/SeriesController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proyect_Rotten_Tomatoes.Data;
using Proyect_Rotten_Tomatoes.Models;

namespace Proyect_Rotten_Tomatoes.Controllers
{
    public class SeriesController : Controller
    {
        private readonly Proyect_Rotten_TomatoesContext _context;

        public SeriesController(Proyect_Rotten_TomatoesContext context)
        {
            _context = context;
        }

        // GET: Series/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Serie == null)
            {
                return NotFound();
            }

            var serie = await _context.Serie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (serie == null)
            {
                return NotFound();
            }

            return View(serie);
        }

        // GET: Series/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Series/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string url)
        {
            if (string.IsNullOrEmpty(url))
            {
                ModelState.AddModelError("url", "Link is required.");
                return View();
            }
            try
            {
                Serie serie = WebScraper.Get_Serie_data(url);
                if (await _context.Serie.SingleOrDefaultAsync(s => s.Title == serie.Title) != null)
                {
                    throw new Exception("Serie already exists");
                }
                _context.Add(serie);
            }
            catch (Exception ex)
            {
                if (ex.Message.Length < 22)
                {
                    ModelState.AddModelError("url", ex.Message);
                }
                else
                {
                    ModelState.AddModelError("url", "Try another link.");
                }
                return View();
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Film_ExpertSeries", "Film_Expert");
        }

            // GET: Series/Edit/5
            public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Serie == null)
            {
                return NotFound();
            }

            var serie = await _context.Serie.FindAsync(id);
            if (serie == null)
            {
                return NotFound();
            }
            return View(serie);
        }

        // POST: Series/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,url,Title,Image,Critic_Rating,Audience_Rating,Available_Platforms,Synopsis,Genre,Serie_Team,Principal_Actors,Premiere_Date,Top")] Serie serie)
        {
            if (id != serie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(serie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SerieExists(serie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Film_ExpertSeries", "Film_Expert");
            }
            return View(serie);
        }

        // GET: Series/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Serie == null)
            {
                return NotFound();
            }

            var serie = await _context.Serie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (serie == null)
            {
                return NotFound();
            }

            return View(serie);
        }

        // POST: Series/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Serie == null)
            {
                return Problem("Entity set 'Proyect_Rotten_TomatoesContext.Serie'  is null.");
            }
            var serie = await _context.Serie.FindAsync(id);
            if (serie != null)
            {
                _context.Serie.Remove(serie);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Film_ExpertSeries", "Film_Expert");
        }

        private bool SerieExists(int id)
        {
          return (_context.Serie?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Cinephiles/CinephileMovies.cshtml
    @model IEnumerable<Proyect_Rotten_Tomatoes.Models.Movie>
    @{

        ViewData["Title"] = "Index";
        Layout = "~/Views/Shared/_Layout_Cinephile.cshtml";
    }

    <style>
        .title {
            writing-mode: vertical-rl;
            transform: rotate(180deg);
            position: fixed;
            left: 0;
            top: 50%;
            margin-top: -80px;
            width: 50px;
            text-align: center;
            font-size: 35px;
        }

        .movies {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-items: center;
            margin: 0 auto;
            max-width: 1100px;
        }
    
        .card {
            margin: 0 auto;
        }
    </style>

    <div class="title">
        MOVIES
    </div>

    <header>
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bi bi-gear"></i> Order by
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-action="CinephileMovies" asp-route-orderBy="CriticRating"><i class="bi bi-camera-reels"></i> Critic Rating</a>
                    <a class="dropdown-item" asp-action="CinephileMovies" asp-route-orderBy="AudienceRating"><i class="bi bi-headset"></i> Critic_Audience </a>
                    <a class="dropdown-item" asp-action="CinephileMovies" asp-route-orderBy="Genre"><i class="bi bi-person-square"></i> Genre </a>
                </div>
            </li>
        </ul>
    </header>
<form asp-action="AddFavoriteMovie">
    <section class="row">
        @foreach (var item in Model)
        {
            <article class="col-md-4 col-xs-5 border-primary mb-3">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header bg-info text-white">
                                <h5 class="card-title">
                                    @item.Title
                                </h5>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img src="@item.Image" class="img-fluid" alt="@item.Title">
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text"><b>Genre: </b>@item.Genre</p>
                                @if(item.Critic_Rating == 1)
                                {
                                    <p class="card-text"><b>Critic rate: </b>--</p>
                                }
                                else
                                {
                                    <p class="card-text"><b>Critic rate: </b>@item.Critic_Rating</p>
                                }
                                <p class="card-text"><b>Audience rate: </b>@item.Audience_Rating</p>
                                <p class="card-text"><b>Duration: </b>@item.Duration</p>
                                <p class="card-text"><b>Release Date: </b>@item.Release_Date</p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer d-flex justify-content-end">
                                <a class="btn btn-outline-primary" asp-controller="Movies" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <form method="post" asp-controller="Cinephiles" asp-action="AddFavoriteMovie">
                                    <input type="hidden" name="movie" value='@Json.Serialize(item)' />
                                    <input type="submit" value="Add Favorite" class="btn btn-danger" />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        }
    </section>
    <button type="submit" class="btn btn-primary">Save Favorite</button>
</form>
    <div class="fixed-bottom d-flex justify-content-between text-white mr-3 mb-3">
        <a asp-action="CinephileTopMovies" class="btn btn-success ml-auto">
            <i class="bi bi-eye-fill"></i> Top Movies
        </a>
        <a asp-action="CinephileSeries" class="btn btn-success ml-auto">
            <i class="bi bi-eye-fill"></i> Series
        </a>
    </div>

Views/Cinephiles/CinephileSeries.cshtml
    @model IEnumerable<Proyect_Rotten_Tomatoes.Models.Serie>

@{
    //ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Cinephile.cshtml";
}

<style>
    .title {
        writing-mode: vertical-rl;
        transform: rotate(180deg);
        position: fixed;
        left: 0;
        top: 50%;
        margin-top: -80px;
        width: 50px;
        text-align: center;
        font-size: 35px;
    }

    .movies {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        margin: 0 auto;
        max-width: 1100px;
    }
    
    .card {
        margin: 0 auto;
    }
</style>

<div class="title">
    SERIES
</div>

<header>
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="bi bi-gear"></i> Order by
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-action="CinephileSeries" asp-route-orderBy="CriticRating"><i class="bi bi-camera-reels"></i> Critic Rating</a>
                <a class="dropdown-item" asp-action="CinephileSeries" asp-route-orderBy="AudienceRating"><i class="bi bi-headset"></i> Critic_Audience </a>
                <a class="dropdown-item" asp-action="CinephileSeries" asp-route-orderBy="Genre"><i class="bi bi-person-square"></i> Genre </a>
            </div>
        </li>
    </ul>
</header>
<form asp-action="AddFavoriteSerie">
<section class="row">
    @foreach (var item in Model)
    {
        <article class="col-md-4 col-xs-5 border-primary mb-3">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header bg-info text-white">
                            <h5 class="card-title">
                                @item.Title
                                <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                            </h5>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.Image" class="img-fluid" alt="@item.Title">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text"><b>Genre: </b>@item.Genre</p>
                            @if (item.Critic_Rating != 1)
                            {
                                <p class="card-text"><b>Critic rate: </b>@item.Critic_Rating</p>
                            }
                            else
                            {
                                <p class="card-text"><b>Critic rate: </b>--</p>
                            }

                            @if (item.Audience_Rating != 1)
                            {
                                <p class="card-text"><b>Audience rate: </b>@item.Audience_Rating</p>
                            }
                            else
                            {
                                <p class="card-text"><b>Audience rate: </b>--</p>
                            }
                            <p class="card-text"><b>Premiere Date: </b>@item.Premiere_Date</p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer d-flex justify-content-end">
                            <a class="btn btn-outline-primary" asp-controller="Series" asp-action="Details" asp-route-id="@item.Id">
                                <i class="bi bi-eye-fill"></i> Show Details
                            </a>
                            <form method="post" asp-controller="Cinephiles" asp-action="AddFavoriteSerie">
                                    <input type="hidden" name="serie" value='@Json.Serialize(item)' />
                                    <input type="submit" value="Add Favorite" class="btn btn-danger" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    }
</section>
</form>
<div class="fixed-bottom d-flex justify-content-between text-white mr-3 mb-3">
    <a asp-action="CinephileTopSeries" class="btn btn-success ml-auto">
        <i class="bi bi-eye-fill"></i> Top Series
    </a>
    <a asp-controller="Cinephiles" asp-action="CinephileMovies" class="btn btn-success ml-auto">
        <i class="bi bi-eye-fill"></i> Movies
    </a>
</div>

Views/Cinephiles/CinephileTopMovies.cshtml
@model IEnumerable<Proyect_Rotten_Tomatoes.Models.Movie>
@{
    ViewData["Title"] = "TopMovies";
    Layout = "~/Views/Shared/_Layout_Cinephile.cshtml";
}
<style>
    .title {
        writing-mode: vertical-rl;
        transform: rotate(180deg);
        position: fixed;
        left: 0;
        top: 50%;
        margin-top: -80px;
        width: 50px;
        text-align: center;
        font-size: 35px;
    }

    .movies {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        margin: 0 auto;
        max-width: 1100px;
    }
    
    .card {
        margin: 0 auto;
    }
</style>

<div class="title">
    TOP MOVIES
</div>

<section class="row">
    @foreach (var item in Model)
    {
        if (item.Top == true)
        {
            <article class="col-md-4 col-xs-5 border-primary mb-3">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header bg-info text-white">
                                <h5 class="card-title">
                                    @item.Title
                                </h5>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img src="@item.Image" class="img-fluid" alt="@item.Title">
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text"><b>Genre: </b>@item.Genre</p>
                                @if(item.Critic_Rating != 1){
                                    <p class="card-text"><b>Critic rate: </b>@item.Critic_Rating</p>
                                }
                                else{
                                    <p class="card-text"><b>Critic rate: </b>--</p>
                                }
                                @if(item.Audience_Rating != 1){
                                <p class="card-text"><b>Audience rate: </b>@item.Audience_Rating</p>
                                }
                                else{
                                    <p class="card-text"><b>Audience rate: </b>--</p>
                                }
                                <p class="card-text"><b>Duration: </b>@item.Duration</p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer d-flex justify-content-end">
                                <a class="btn btn-outline-primary" asp-controller="Movies" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <form method="post" asp-controller="Cinephiles" asp-action="AddFavoriteMovie">
                                    <input type="hidden" name="movie" value='@Json.Serialize(item)' />
                                    <input type="submit" value="Add Favorite" class="btn btn-danger" />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        }
    }
</section>
<div class="fixed-bottom d-flex justify-content-between text-white mr-3 mb-3">
    <a asp-action="CinephileMovies" class="btn btn-success ml-auto">
        <i class="bi bi-plus-circle"></i> All Movies
    </a>
</div>

Views/Cinephiles/Create.cshtml
@model Proyect_Rotten_Tomatoes.Models.Cinephile

@{
    ViewData["Title"] = "Create";
}
<h2>Cinephile</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sign Up" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Cinephiles/Favourites.cshtml
@model Favorites
@{
    Layout = "~/Views/Shared/_Layout_Cinephile.cshtml";
 }
<h2>Favorite Movies</h2>
<header>
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="bi bi-gear"></i> Order by
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-action="Favourites" asp-route-orderBy="CriticRating"><i class="bi bi-camera-reels"></i> Critic Rating</a>
                <a class="dropdown-item" asp-action="Favourites" asp-route-orderBy="AudienceRating"><i class="bi bi-headset"></i> Critic_Audience </a>
                <a class="dropdown-item" asp-action="Favourites" asp-route-orderBy="Genre"><i class="bi bi-person-square"></i> Genre </a>
            </div>
        </li>
    </ul>
</header>
<section class="row">
        @foreach (var item in Model.Movies)
        {
            <article class="col-md-4 col-xs-5 border-primary mb-3">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header bg-info text-white">
                                <h5 class="card-title">
                                    @item.Title
                                </h5>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img src="@item.Image" class="img-fluid" alt="@item.Title">
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text"><b>Genre: </b>@item.Genre</p>
                                @if(item.Critic_Rating == 1)
                                {
                                    <p class="card-text"><b>Critic rate: </b>--</p>
                                }
                                else
                                {
                                    <p class="card-text"><b>Critic rate: </b>@item.Critic_Rating</p>
                                }
                                @if(item.Audience_Rating == 1)
                                {
                                    <p class="card-text"><b>Audience rate: </b>--</p>
                                }
                                else
                                {
                                    <p class="card-text"><b>Audience rate: </b>@item.Audience_Rating</p>
                                }
                                <p class="card-text"><b>Duration: </b>@item.Duration</p>
                                <p class="card-text"><b>Release Date: </b>@item.Release_Date</p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer d-flex justify-content-end">
                                <a class="btn btn-outline-primary" asp-controller="Movies" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        }
    </section>

<h2>Favorite Series</h2>
<section class="row">
    @foreach (var item in Model.Series)
    {
        <article class="col-md-4 col-xs-5 border-primary mb-3">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header bg-info text-white">
                            <h5 class="card-title">
                                @item.Title
                                <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                            </h5>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.Image" class="img-fluid" alt="@item.Title">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text"><b>Genre: </b>@item.Genre</p>
                            @if (item.Critic_Rating != 1)
                            {
                                <p class="card-text"><b>Critic rate: </b>@item.Critic_Rating</p>
                            }
                            else
                            {
                                <p class="card-text"><b>Critic rate: </b>--</p>
                            }

                            @if (item.Audience_Rating != 1)
                            {
                                <p class="card-text"><b>Audience rate: </b>@item.Audience_Rating</p>
                            }
                            else
                            {
                                <p class="card-text"><b>Audience rate: </b>--</p>
                            }
                            <p class="card-text"><b>Premiere Date: </b>@item.Premiere_Date</p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer d-flex justify-content-end">
                            <a class="btn btn-outline-primary" asp-controller="Series" asp-action="Details" asp-route-id="@item.Id">
                                <i class="bi bi-eye-fill"></i> Show Details
                            </a>
                            <form method="post" asp-controller="Cinephiles" asp-action="AddFavoriteSerie">
                                    <input type="hidden" name="serie" value='@Json.Serialize(item)' />
                                    <input type="submit" value="Add Favorite" class="btn btn-danger" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    }
</section>